name: Release
"on":
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  release-plz-release:
    if: "${{ github.repository_owner == 'tokio-rs' }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe
      - uses: release-plz/action@064f4d1e36c843611ddf013be726beaa4ad804db
        with:
          command: release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  release-plz-pr:
    if: "${{ !failure() && github.repository_owner == 'tokio-rs' }}"
    needs: release-plz-release
    runs-on: ubuntu-latest
    concurrency:
      group: "release-plz-${{ github.ref }}"
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: release-plz/action@064f4d1e36c843611ddf013be726beaa4ad804db
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"